(import (scheme base)
	(rapid test)
	(rename (rapid test test) (run-tests run-rapid-test-tests))
        (rename (rapid and-let test) (run-tests run-rapid-and-let-tests))
	(rename (rapid boxes test) (run-tests run-rapid-boxes-tests))
        (rename (rapid comparators test) (run-tests run-rapid-comparators-tests))
	(rename (rapid lists test) (run-tests run-rapid-lists-tests))
        (rename (rapid tables test) (run-tests run-rapid-tables-tests))
        (rename (rapid sets test) (run-tests run-rapid-sets-tests))
        (rename (rapid maps test) (run-tests run-rapid-maps-tests))
	(rename (rapid generators test) (run-tests run-rapid-generators-tests))
        (rename (rapid format test) (run-tests run-rapid-format-tests))
	(rename (rapid paths test) (run-tests run-rapid-paths-tests)))

(test-begin "Rapid Libraries")

(run-rapid-test-tests)
(run-rapid-and-let-tests)
(run-rapid-boxes-tests)
(run-rapid-generators-tests)
(run-rapid-lists-tests)
(run-rapid-tables-tests)
(run-rapid-sets-tests)
(run-rapid-maps-tests)
(run-rapid-generators-tests)
(run-rapid-format-tests)
(run-rapid-paths-tests)

(test-end "Rapid Libraries")
